services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pr-mngt-db  # Database name set as mongoosedb
      - PORT=4000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:4000  # Backend URL

  mongo:
    image: mongo
    ports:
      - "27017:27017"  # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data: