services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"  # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:
  uploads_data: